# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
server/src/main/resources/openAPI/sidecarApi.yaml:
  info-license:
    - '#/info'
  operation-4xx-response:
    - '#/paths/~1__health/get/responses'
    - '#/paths/~1cassandra~1__health/get/responses'
    - '#/paths/~1cassandra~1native~1__health/get/responses'
    - '#/paths/~1cassandra~1jmx~1__health/get/responses'
    - >-
      #/paths/~1keyspace~1{keyspace}~1table~1{table}~1snapshots~1{snapshot}~1components~1{component}/get/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1snapshots~1{snapshot}~1components~1{component}/get/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1snapshots~1{snapshot}~1components~1{index}~1{component}/get/responses
    - >-
      #/paths/~1keyspace~1{keyspace}~1table~1{table}~1snapshots~1{snapshot}/get/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1snapshots~1{snapshot}/get/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1snapshots~1{snapshot}/put/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1snapshots~1{snapshot}/delete/responses
    - '#/paths/~1schema~1keyspaces/get/responses'
    - '#/paths/~1cassandra~1schema/get/responses'
    - '#/paths/~1schema~1keyspaces~1{keyspace}/get/responses'
    - '#/paths/~1keyspaces~1{keyspace}~1schema/get/responses'
    - '#/paths/~1cassandra~1ring/get/responses'
    - '#/paths/~1cassandra~1ring~1keyspaces~1{keyspace}/get/responses'
    - '#/paths/~1cassandra~1stats~1stats~1connected-clients/get/responses'
    - '#/paths/~1keyspaces~1{keyspace}~1token-range-replicas/get/responses'
    - >-
      #/paths/~1uploads~1{uploadId}~1keyspaces~1{keyspace}~1tables~1{table}~1components~1{component}/put/responses
    - >-
      #/paths/~1uploads~1{uploadId}~1keyspaces~1{keyspace}~1tables~1{table}~1import/put/responses
    - '#/paths/~1uploads~1{uploadId}/delete/responses'
    - '#/paths/~1cassandra~1gossip/get/responses'
    - '#/paths/~1time-skew/get/responses'
    - '#/paths/~1cassandra~1settings/get/responses'
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1restore-jobs/post/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1restore-jobs~1{jobId}~1slices/post/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1restore-jobs~1{jobId}/get/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1restore-jobs~1{jobId}/patch/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1restore-jobs~1{jobId}~1abort/post/responses
    - >-
      #/paths/~1keyspaces~1{keyspace}~1tables~1{table}~1restore-jobs~1{jobId}~1progress/get/responses
    - '#/paths/~1cdc~1segments/get/responses'
    - '#/paths/~1cdc~1segments~1{cdcSegment}/get/responses'
