get:
  tags:
    - settings
  operationId: nodeSettings
  description: Get the settings of a node
  summary: Endpoint used to retrieve the current settings of a Cassandra node
  security:
    - mTLS: []
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../components/schemas/nodeSettings.yaml
