/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.cassandra.sidecar.handlers;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import io.netty.handler.codec.http.HttpResponseStatus;
import io.vertx.core.Handler;
import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.ext.web.RoutingContext;

/**
 * Handler that serves the OpenAPI specification
 * 
 * This handler serves the OpenAPI specification generated by the Gradle generateOpenApiSpec task
 * which processes JAX-RS/MicroProfile annotations to create comprehensive API documentation.
 */
@Singleton
public class OpenApiHandler implements Handler<RoutingContext>
{
    private static final Logger LOGGER = LoggerFactory.getLogger(OpenApiHandler.class);
    private final Vertx vertx;

    @Inject
    public OpenApiHandler(Vertx vertx)
    {
        this.vertx = vertx;
    }

    @Override
    public void handle(RoutingContext context)
    {
        try
        {
            // Determine format from request path or Accept header
            boolean isYaml = isYamlRequest(context);
            String openApiContent = loadGeneratedOpenApiSpec(isYaml);
            String contentType = isYaml ? "application/yaml" : "application/json";
            
            context.response()
                   .putHeader("Content-Type", contentType)
                   .end(openApiContent);
        }
        catch (Exception e)
        {
            context.response().setStatusCode(HttpResponseStatus.NOT_FOUND.code())
                   .putHeader("Content-Type", "application/json")
                   .end();
        }
    }

    /**
     * Determines if the request is for YAML format based on path or Accept header
     */
    private boolean isYamlRequest(RoutingContext context)
    {
        String path = context.request().path();
        if (path != null && path.endsWith(".yaml"))
        {
            return true;
        }
        
        String acceptHeader = context.request().getHeader("Accept");
        return acceptHeader != null && acceptHeader.contains("application/yaml");
    }
    
    /**
     * Loads the generated OpenAPI specification from resources or build output
     */
    private String loadGeneratedOpenApiSpec(boolean isYaml) throws IOException
    {
        // First try to load from classpath resources (for packaged deployments)
        String content = loadFromClasspathResource(isYaml);
        if (content != null)
        {
            return content;
        }

        // Fallback to file system paths (for development)
        return loadFromFileSystem(isYaml);
    }

    /**
     * Attempts to load the OpenAPI spec from classpath resources
     */
    private String loadFromClasspathResource(boolean isYaml) throws IOException
    {
        String fileName = isYaml ? "openapi.yaml" : "openapi.json";
        String resourcePath = "/openapi/" + fileName;
        
        InputStream inputStream = getClass().getResourceAsStream(resourcePath);
        if (inputStream == null)
        {
            return null;
        }
        
        LOGGER.debug("Loading OpenAPI specification from classpath: {}", resourcePath);
        try 
        {
            byte[] bytes = inputStream.readAllBytes();
            String content = new String(bytes, StandardCharsets.UTF_8);
            LOGGER.info("Loaded OpenAPI specification from classpath resource");
            return content;
        }
        finally
        {
            inputStream.close();
        }
    }

    /**
     * Attempts to load the OpenAPI spec from file system (development mode)
     */
    private String loadFromFileSystem(boolean isYaml) throws IOException
    {
        String fileName = isYaml ? "openapi.yaml" : "openapi.json";
        String[] possiblePaths = {
            "server/build/generated/openapi/" + fileName,    // From project root
            "build/generated/openapi/" + fileName,           // From server directory
            "../server/build/generated/openapi/" + fileName, // Alternative relative path
        };
        
        String foundPath = null;
        for (String pathStr : possiblePaths)
        {
            if (vertx.fileSystem().existsBlocking(pathStr))
            {
                foundPath = pathStr;
                break;
            }
        }
        
        if (foundPath == null)
        {
            throw new IOException("Generated OpenAPI specification not found in classpath resources or file system. " +
                                "Please run './gradlew generateOpenApiSpec' and ensure the generated file is included in the build.");
        }
        
        LOGGER.debug("Loading OpenAPI specification from: {}", foundPath);
        Buffer buffer = vertx.fileSystem().readFileBlocking(foundPath);
        String content = buffer.toString();
        LOGGER.info("Loaded OpenAPI specification from {}", foundPath);
        
        return content;
    }
}
