/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.cassandra.sidecar.handlers;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collections;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import io.swagger.v3.core.util.Json;
import io.swagger.v3.oas.models.OpenAPI;
import io.vertx.core.Handler;
import io.vertx.ext.web.RoutingContext;
import org.apache.cassandra.sidecar.config.OpenApiConfiguration;
import org.apache.cassandra.sidecar.config.SidecarConfiguration;

/**
 * Handler that serves the OpenAPI specification
 * 
 * This handler serves the OpenAPI specification generated by the Gradle openApiGenerate task
 * which processes JAX-RS/MicroProfile annotations to create comprehensive API documentation.
 */
@Singleton
public class OpenApiHandler implements Handler<RoutingContext>
{
    private static final Logger logger = LoggerFactory.getLogger(OpenApiHandler.class);
    private final OpenApiConfiguration openApiConfig;
    
    // Cache for both JSON and YAML specifications
    private volatile String cachedJsonSpec;
    private volatile String cachedYamlSpec;
    private volatile long lastModified;

    @Inject
    public OpenApiHandler(SidecarConfiguration sidecarConfiguration)
    {
        this.openApiConfig = sidecarConfiguration.openApiConfiguration();
    }

    @Override
    public void handle(RoutingContext context)
    {
        try
        {
            // Determine format from request path or Accept header
            boolean isYaml = isYamlRequest(context);
            String openApiContent = loadGeneratedOpenApiSpec(isYaml);
            String contentType = isYaml ? "application/yaml" : "application/json";
            
            context.response()
                   .putHeader("Content-Type", contentType)
                   .end(openApiContent);
        }
        catch (Exception e)
        {
            logger.warn("Failed to load generated OpenAPI specification, falling back to basic config", e);
            
            // Fallback to basic OpenAPI config if generated file is not available
            OpenAPI openAPI = createOpenApiFromConfig(openApiConfig);
            String openApiJson = Json.pretty(openAPI);
            
            context.response()
                   .putHeader("Content-Type", "application/json")
                   .end(openApiJson);
        }
    }

    /**
     * Determines if the request is for YAML format based on path or Accept header
     */
    private boolean isYamlRequest(RoutingContext context)
    {
        String path = context.request().path();
        if (path != null && path.endsWith(".yaml"))
        {
            return true;
        }
        
        String acceptHeader = context.request().getHeader("Accept");
        return acceptHeader != null && acceptHeader.contains("application/yaml");
    }
    
    /**
     * Loads the generated OpenAPI specification from resources or build output with caching
     */
    private String loadGeneratedOpenApiSpec(boolean isYaml) throws IOException
    {
        // First try to load from classpath resources (for packaged deployments)
        String cached = isYaml ? cachedYamlSpec : cachedJsonSpec;
        if (cached == null)
        {
            cached = loadFromClasspathResource(isYaml);
            if (isYaml)
            {
                cachedYamlSpec = cached;
            }
            else
            {
                cachedJsonSpec = cached;
            }
        }
        
        if (cached != null)
        {
            return cached;
        }

        // Fallback to file system paths (for development)
        return loadFromFileSystem(isYaml);
    }

    /**
     * Attempts to load the OpenAPI spec from classpath resources
     */
    private String loadFromClasspathResource(boolean isYaml) throws IOException
    {
        String fileName = isYaml ? "openapi.yaml" : "openapi.json";
        String resourcePath = "/openapi/" + fileName;
        InputStream inputStream = getClass().getResourceAsStream(resourcePath);
        if (inputStream == null)
        {
            return null;
        }
        
        try
        {
            logger.debug("Loading OpenAPI specification from classpath: {}", resourcePath);
            String content = new String(inputStream.readAllBytes(), StandardCharsets.UTF_8);
            logger.info("Loaded OpenAPI specification from classpath resource");
            return content;
        }
        finally
        {
            inputStream.close();
        }
    }

    /**
     * Attempts to load the OpenAPI spec from file system (development mode)
     */
    private String loadFromFileSystem(boolean isYaml) throws IOException
    {
        String fileName = isYaml ? "openapi.yaml" : "openapi.json";
        String[] possiblePaths = {
            "server/build/generated/openapi/" + fileName,    // From project root
            "build/generated/openapi/" + fileName,           // From server directory
            "../server/build/generated/openapi/" + fileName, // Alternative relative path
        };
        
        Path foundPath = null;
        for (String pathStr : possiblePaths)
        {
            Path path = Paths.get(pathStr);
            if (Files.exists(path))
            {
                foundPath = path;
                break;
            }
        }
        
        if (foundPath == null)
        {
            throw new IOException("Generated OpenAPI specification not found in classpath resources or file system. " +
                                "Please run './gradlew openApiGenerate' and ensure the generated file is included in the build.");
        }
        
        // Check if we need to reload the file (if it's newer than our cached version)
        long fileLastModified = Files.getLastModifiedTime(foundPath).toMillis();
        String cached = isYaml ? cachedYamlSpec : cachedJsonSpec;
        if (cached == null || fileLastModified > lastModified)
        {
            logger.debug("Loading OpenAPI specification from: {}", foundPath.toAbsolutePath());
            String content = Files.readString(foundPath, StandardCharsets.UTF_8);
            lastModified = fileLastModified;
            logger.info("Loaded OpenAPI specification from {}", foundPath.toAbsolutePath());
            
            // Update the appropriate cache
            if (isYaml)
            {
                cachedYamlSpec = content;
            }
            else
            {
                cachedJsonSpec = content;
            }
            
            return content;
        }
        
        return cached;
    }
    
    /**
     * Creates a basic OpenAPI configuration as fallback when generated spec is not available
     */
    private static OpenAPI createOpenApiFromConfig(OpenApiConfiguration config)
    {
        OpenAPI openApi = new OpenAPI();
        
        // Set basic info
        io.swagger.v3.oas.models.info.Info info = new io.swagger.v3.oas.models.info.Info();
        info.setTitle(config.title());
        info.setDescription(config.description() + " (Generated specification not available - run './gradlew openApiGenerate')");
        info.setVersion(config.version());
        
        // Set license info
        io.swagger.v3.oas.models.info.License license = new io.swagger.v3.oas.models.info.License();
        license.setName(config.licenseName());
        license.setUrl(config.licenseUrl());
        info.setLicense(license);
        
        openApi.setInfo(info);
        
        // Set server info
        io.swagger.v3.oas.models.servers.Server server = new io.swagger.v3.oas.models.servers.Server();
        server.setUrl(config.serverUrl());
        server.setDescription(config.serverDescription());
        openApi.setServers(Collections.singletonList(server));
        
        return openApi;
    }
}
